server:
  port: 8083

spring:
  application:
    name: ms-viajeros

  datasource:
    url: jdbc:mysql://localhost:3307/db_viajeros?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
